"""empty message

Revision ID: 8688b031befa
Revises: d7da43dfd07f
Create Date: 2020-05-20 19:00:56.966516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8688b031befa'
down_revision = 'd7da43dfd07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_next_due', table_name='budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_budget_next_due', 'budget', ['next_due'], unique=False)
    # ### end Alembic commands ###
