"""empty message

Revision ID: abbafbe57a72
Revises: d000529fcda5
Create Date: 2020-02-22 10:31:27.793008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbafbe57a72'
down_revision = 'd000529fcda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=140), nullable=True),
    sa.Column('expense', sa.String(length=140), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('last_paid', sa.DateTime(), nullable=True),
    sa.Column('expense_cycle', sa.Integer(), nullable=True),
    sa.Column('in_flows', sa.Integer(), nullable=True),
    sa.Column('out_flows', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_last_paid'), 'budget', ['last_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_last_paid'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
