"""empty message

Revision ID: d000529fcda5
Revises: 77c14bee4e5e
Create Date: 2020-02-22 10:30:51.669667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd000529fcda5'
down_revision = '77c14bee4e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_last_paid', table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group', sa.VARCHAR(length=140), nullable=True),
    sa.Column('expense', sa.VARCHAR(length=140), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('last_paid', sa.DATETIME(), nullable=True),
    sa.Column('expense_cycle', sa.INTEGER(), nullable=True),
    sa.Column('in_flows', sa.INTEGER(), nullable=True),
    sa.Column('out_flows', sa.INTEGER(), nullable=True),
    sa.Column('available', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_last_paid', 'budget', ['last_paid'], unique=False)
    # ### end Alembic commands ###
